apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: filmclubwts2020/frontendapp
        imagePullPolicy: Always  #always because it get always latest version from dockerhub
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:  
            name: frontend-secret 
      

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: static-files
        persistentVolumeClaim:
          claimName: static-files-claim
      containers:
      - name: backend
        image: filmclubwts2020/backendapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        envFrom:
        - secretRef:  
            name: backend-secret 
        volumeMounts:
        - mountPath: /usr/src/app/public/images
          name: static-files
      
      