apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-deployment
  labels:
    name:  backend-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  backend-deployment
    spec:
      containers:
      - image:  filmclubwts2020/backend
        name:  backend-deployment
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5002
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5002
          initialDelaySeconds: 30
          timeoutSeconds: 10
        envFrom:
        - secretRef:  
            name: backend-secret     
        ports:
        - containerPort:  5002
          name:  backend-deployment
        volumeMounts:
        - mountPath: /usr/src/app/public/images
          name: static_files
      volumes:
        - name: static_files
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  labels:
    name:  frontend-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  frontend-deployment
    spec:
      containers:
      - image:  filmclubwts2020/frontend
        name:  frontend-deployment
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5173
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5173
          initialDelaySeconds: 30
          timeoutSeconds: 10
        envFrom:
        - secretRef:  
            name: frontend-secret      
        ports:
        - containerPort:  5173
          name:  frontend-deployment
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always