apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-deployment
  labels:
    name:  backend
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  backend
    spec:
      containers:
      - image:  filmclubwts2020/backend
        name:  backend
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5002
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5002
          initialDelaySeconds: 30
          timeoutSeconds: 10
        envFrom:
        - secretRef:  
            name: backend-secret     
        ports:
        - containerPort: 5002
          name:  backend
        volumeMounts:
        - mountPath: "/usr/src/app/public/images"
          name: static_files
      volumes:
        - name: static_files
          persistentVolumeClaim:
              claimName: static_files
      restartPolicy: Always
      

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  labels:
    name:  frontend
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  frontend
    spec:
      containers:
      - image:  filmclubwts2020/frontend
        name:  frontend
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5173
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5173
          initialDelaySeconds: 30
          timeoutSeconds: 10
        envFrom:
        - secretRef:  
            name: frontend-secret      
        ports:
        - containerPort:  5173
          name:  frontend
        volumeMounts:
        - mountPath: "/data"
          name: data
      volumes:
        - name: data
      restartPolicy: Always
      