apiVersion: v1
kind: Secret
metadata:
  name:  backend-secret
type: Opaque
data:
   PORT: 
   MONGO_URI: 
   NODE_ENV: 
   PROFILE_PICTURE_PATH:
   CORS_HOST: 
   JWT_SECRET: 
   JWT_LIFETIME: 
   COOKIE_MAX_AGE:
   CRYPTOJS_KEY: 
--- 

apiVersion: v1
kind: Secret
metadata:
  name:  frontend-secret
type: Opaque
data:
   VITE_CRYPTOJS_KEY: 
   VITE_API_URL: 

---



