kind: Service
apiVersion: v1
metadata:
  name:  backend-service
spec:
  selector:
    app:  backend
  type:  ClusterIP
  ports:
  - name:  backend-port
    port:  5002
    targetPort:  5002

    

---

kind: Service
apiVersion: v1
metadata:
  name:  frontend-service
spec:
  selector:
    app:  frontend
  type:  NodePort
  ports:
  - name:  frontend-port
    port:  80
    targetPort:  5173
