kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - name: backend-port
    port: 5002
    targetPort: 5002

---

kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - name: frontend-port
    port: 5173
    targetPort: 5173

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 5173