apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---