apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1 
kind: PersistentVolume
metadata:
  name:  static-files
  labels:
    name: static-files
spec:
  capacity: 
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
