apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-file-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/nfs_share"
    server: 164.92.184.155

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi