apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

