apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

--- 

apiVersion: v1 
kind: PersistentVolume
metadata:
  name: static-files-storage
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  hostPath:
    path: "/usr/src/app/public/images"