name: Build Containers for Production & Push to Dockerhub

on:
  workflow_dispatch: 
  # push:
  #   branches:
  #     - master

jobs:
  Deploy_Images_DockerHub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push Server
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          push: true
          tags: filmclubwts2020/backend
      -
        name: Build and push Client
        uses: docker/build-push-action@v3
        with:
          context: ./frontend/
          push: true
          tags: filmclubwts2020/frontend
  
  Deploy_Kubernetes:
    runs-on: ubuntu-latest
    needs: Deploy_Images_DockerHub
    steps:
      - name : Checkout
        uses: actions/checkout@v3
      
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with: 
          token:${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      
      - name: Apply secrets 
        run: kubectl apply -f $GITHUB_WORKSPACE/k8s/service.yaml

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 movielibrary-kubernetes-cluster
      
      - name: Deploy to DigitalOcean Kubernetes cluster
        run: kubectl apply -f $GITHUB_WORKSPACE/k8s/deployment.yaml
      
      - name: Verify Deployment of backend 
        run: kubectl rollout status deployment/backend-deployment
      
       
      - name: Verify Deployment of frontend 
        run: kubectl rollout status deployment/frontend-deployment



       
    
          
     
